// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlgvjvbquqzsusnsmjlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZ3ZqdmJxdXF6c3VzbnNtamxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjM5MjMsImV4cCI6MjA1ODc5OTkyM30.rJo6XTvWniDtCt6nDyGH6iRwtVvGd8ZZRCXrVKy9EEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});